# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Run tests (Java CI with Maven)

on:
  push:
    branches:  [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup java
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Check out repo with test data
      run: git clone https://miguelfbrito:${{ secrets.token_actions }}@github.com/miguelfbrito/thesis-web-applications
    - name: Run tests 
      run: mvn test
      working-directory: ./symbolsolver
